const { faker } = require("@faker-js/faker");
const bcrypt = require("bcrypt");
const hashPassword = (pwd) => bcrypt.hashSync(pwd, bcrypt.genSaltSync(10));

module.exports = {
  roles: [
    {
      code: "ROL1",
      value: "Quản trị viên",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      code: "ROL3",
      value: "Chủ tài sản",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      code: "ROL5",
      value: "Môi giới",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      code: "ROL7",
      value: "Khách hàng",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],

  users: Array.from({ length: 10 }).map((_, index) => ({
    name: faker.helpers.arrayElement([
      "Nguyễn Văn A",
      "Trần Thị B",
      "Lê Hoàng C",
      "Phạm Minh D",
      "Bùi Thị E",
      "Hoàng Văn F",
      "Nguyễn Thị G",
      "Trần Văn H",
      "Phan Minh I",
      "Lê Văn J",
    ]),
    phone: "0" + faker.string.numeric(9), // random 9 số
    email: `user${index + 1}@gmail.com`,
    address: faker.location.streetAddress({ useFullAddress: true }),
    password: hashPassword("123456"),
    avatar: faker.image.avatar(),
    createdAt: new Date(),
    updatedAt: new Date(),
  })),

  user_roles: [
    ...Array.from([...Array(10).keys()]).map((el) => ({
      userId: el + 1,
      roleCode: "ROL7",
      createdAt: new Date(),
      updatedAt: new Date(),
    })),
    {
      userId: 7,
      roleCode: "ROL3",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      userId: 8,
      roleCode: "ROL5",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      userId: 9,
      roleCode: "ROL3",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      userId: 10,
      roleCode: "ROL1",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],

  property_types: [
    {
      name: "Căn hộ chung cư",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "apartment",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Chung cư mini, căn hộ dịch vụ",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "smallapartment",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Nhà riêng",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "house",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Nhà biệt thự, liền kề",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "villa",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Nhà mặt phố",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "townhouse",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Shophouse, nhà phố thương mại",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "shophouse",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Đất nền dự án",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "landproject",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Đất",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "land",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Trang trại, khu nghỉ dưỡng",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "farmresort",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Condotel",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "condotel",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Kho, nhà xưởng",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "warehouse",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Nhà trọ, phòng trọ",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "rentalhouse",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Văn phòng",
      image: faker.image.urlLoremFlickr({
        width: 1000,
        height: 500,
        category: "office",
      }),
      description: faker.lorem.sentences({ min: 2, max: 3 }),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],

  properties: Array.from([...Array(60).keys()]).map(() => ({
    name: faker.helpers.arrayElement([
      "Căn hộ cao cấp tại trung tâm Thành phố Hồ Chí Minh",
      "Biệt thự sang trọng ở ngoại ô Hà Nội",
      "Căn hộ ven biển tại Đà Nẵng",
      "Nhà phố hiện đại tại Hải Phòng",
      "Dự án khu dân cư tại Cần Thơ",
      "Nhà vườn tại An Giang",
      "Căn hộ thông minh tại Bình Dương",
      "Biệt thự nghỉ dưỡng ở Nha Trang",
      "Dự án đất nền tại Đồng Nai",
      "Nhà phố tại Long An",
      "Căn hộ view biển ở Phú Quốc",
      "Khu dân cư tại Vĩnh Long",
      "Căn hộ cao cấp tại Quảng Ninh",
      "Nhà phố ở Hà Giang",
      "Biệt thự nghỉ dưỡng tại Bến Tre",
      "Căn hộ tiện nghi tại Mũi Né",
      "Dự án đất nền tại Khánh Hòa",
      "Căn hộ hiện đại tại Đà Lạt",
      "Nhà phố tại Nam Định",
      "Khu dân cư cao cấp tại Thừa Thiên Huế",
    ]),
    description: faker.helpers.arrayElement([
      "Một không gian sống hiện đại với đầy đủ tiện ích, gần các trung tâm mua sắm.",
      "Không gian yên tĩnh, thích hợp cho gia đình và nghỉ dưỡng cuối tuần.",
      "Nơi lý tưởng để thư giãn và tận hưởng ánh nắng mặt trời.",
      "Thiết kế thông minh, gần gũi với thiên nhiên và tiện ích xung quanh.",
      "Một cộng đồng sống thân thiện với nhiều dịch vụ tiện ích.",
      "Mô hình sống xanh, hòa mình với thiên nhiên và không khí trong lành.",
      "Thiết kế hiện đại với công nghệ tiên tiến, đáp ứng nhu cầu sống hiện đại.",
      "Nơi lý tưởng cho kỳ nghỉ với bãi biển đẹp và tiện nghi đầy đủ.",
      "Cơ hội đầu tư sinh lời cao với vị trí chiến lược phát triển.",
      "Mô hình sống hiện đại gần gũi với cộng đồng, không khí trong lành.",
      "Thiết kế sang trọng, tận hưởng không gian nghỉ dưỡng tuyệt vời.",
      "Môi trường sống bình yên, gần gũi với thiên nhiên.",
      "Nơi lý tưởng cho cuộc sống và đầu tư với các tiện ích đa dạng.",
      "Không gian sống hiện đại, gần gũi với thiên nhiên tuyệt đẹp.",
      "Nơi lý tưởng để thư giãn và trải nghiệm cuộc sống miền Tây.",
      "Hòa mình vào thiên nhiên và tận hưởng bãi biển tuyệt đẹp.",
      "Cơ hội đầu tư hấp dẫn với vị trí đắc địa và tiềm năng phát triển.",
      "Không khí trong lành và cảnh đẹp thiên nhiên, lý tưởng cho nghỉ dưỡng.",
      "Thiết kế hiện đại, tiện ích đầy đủ cho cuộc sống năng động.",
      "Môi trường sống trong lành, gần gũi với văn hóa và lịch sử.",
    ]),
    address: faker.location.streetAddress({ useFullAddress: true }),
    city: faker.helpers.arrayElement([
      "Thành phố Hồ Chí Minh",
      "Hà Nội",
      "Đà Nẵng",
      "Hải Phòng",
      "Cần Thơ",
      "An Giang",
      "Bà Rịa - Vũng Tàu",
      "Bắc Giang",
      "Bắc Kạn",
      "Bạc Liêu",
      "Bắc Ninh",
      "Bến Tre",
      "Bình Định",
      "Bình Dương",
      "Bình Phước",
      "Bình Thuận",
      "Cà Mau",
      "Cao Bằng",
      "Đắk Lắk",
      "Đắk Nông",
      "Điện Biên",
      "Đồng Nai",
      "Đồng Tháp",
      "Gia Lai",
      "Hà Giang",
      "Hà Nam",
      "Hà Tĩnh",
      "Hải Dương",
      "Hậu Giang",
      "Hòa Bình",
      "Hưng Yên",
      "Khánh Hòa",
      "Kiên Giang",
      "Kon Tum",
      "Lai Châu",
      "Lâm Đồng",
      "Lạng Sơn",
      "Lào Cai",
      "Long An",
      "Nam Định",
      "Nghệ An",
      "Ninh Bình",
      "Ninh Thuận",
      "Phú Thọ",
      "Phú Yên",
      "Quảng Bình",
      "Quảng Nam",
      "Quảng Ngãi",
      "Quảng Ninh",
      "Quảng Trị",
      "Sóc Trăng",
      "Sơn La",
      "Tây Ninh",
      "Thái Bình",
      "Thái Nguyên",
      "Thanh Hóa",
      "Thừa Thiên Huế",
      "Tiền Giang",
      "Trà Vinh",
      "Tuyên Quang",
      "Vĩnh Long",
      "Vĩnh Phúc",
      "Yên Bái",
      "Bình Thuận",
      "Bình Phước",
      "Nghệ An",
    ]),
    listingType: faker.helpers.arrayElement(["Bán", "Cho thuê"]),
    price: faker.number.int({ max: 1000000, min: 1000 }) * 1000,
    propertyTypeId: faker.number.int({ max: 13, min: 1 }),
    owner: faker.helpers.arrayElement([7, 9]),
    status: "Chờ duyệt",
    isAvailable: true,
    featuredImage: faker.image.urlLoremFlickr({ category: "realestate" }),
    images: JSON.stringify(
      Array.from([...Array(faker.number.int({ max: 7, min: 5 })).keys()]).map(
        () =>
          `${faker.image.urlLoremFlickr({
            category: "realestate",
          })}?random=${faker.string.numeric(30)}`
      )
    ),
    postedBy: faker.helpers.arrayElement([7, 8, 9]),
    bedRoom: faker.number.int({ max: 3, min: 1 }),
    bathRoom: faker.number.int({ max: 3, min: 1 }),
    propertySize: faker.number.int({ max: 200, min: 20 }),
    yearBuilt: faker.number.int({ max: 2024, min: 1945 }),
    createdAt: new Date(),
    updatedAt: new Date(),
  })),

  membership_plans: [
    {
      name: "Miễn phí",
      price: 0,
      description: "Phù hợp với tất cả mọi người",
      postLimit: 1,
      postDate: 7,
      duration: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cơ bản",
      price: 100000,
      description: "Phù hợp với môi giới mới hoặc giỏ hàng nhỏ",
      postLimit: 2,
      postDate: 14,
      duration: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Tiêu chuẩn",
      price: 500000,
      description: "Phù hợp với môi giới chuyên nghiệp có giỏ hàng từ 5 BDS",
      postLimit: 5,
      postDate: 30,
      duration: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cao cấp",
      price: 1000000,
      description:
        "Phù hợp với môi giới có giỏ hàng và ngân sách quảng cáo lớn",
      postLimit: 10,
      postDate: 60,
      duration: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
};
